/**
 * Structured per-destination data for the "15 cheapest countries" listicle
 * template's destination cards (Phase 1: this template only). Keyed by blog
 * post slug. This is the source of truth for DestinationCardList — the
 * numbered "## N. Country — Subtitle" markdown sections in these posts have
 * been replaced by a single "## Your Cheapest Picks, Ranked" marker heading
 * (see BlogPostPage's DESTINATION_LIST_MARKER split), so the prose here is
 * the only place that content still lives.
 *
 * countryName MUST exactly match a public.destination_photo_countries.country_name
 * row (see scripts/destination-photos/countries.mjs) so DestinationCardList can
 * join photo + daily-cost data. countryCode is ISO 3166-1 alpha-2, used for the
 * flagcdn.com flag and must match countries.mjs too.
 *
 * entryNote is a qualitative planning cue, not a verified visa rule — every
 * post already tells readers to confirm on the Visa Wizard before booking,
 * and DestinationCardList repeats that caveat once per page. Avoid inventing
 * precise fees/durations we haven't sourced; prefer the general pattern
 * ("eVisa — confirm cost", "Visa-free — confirm for your passport") unless
 * the fact is well-established (e.g. ECOWAS free movement, Schengen).
 */

export interface DestinationListItem {
  countryName: string
  countryCode: string
  subtitle: string
  entryNote: string
  gettingThere: string
  valueFeel: 'Outstanding' | 'Excellent' | 'Very good' | 'Good'
  body: string
}

export const DESTINATION_LIST_MARKER = 'Your Cheapest Picks, Ranked'

export const DESTINATION_LIST_ITEMS: Record<string, DestinationListItem[]> = {
  '15-cheapest-countries-to-visit-from-nigeria-in-2026': [
    { countryName: 'Benin', countryCode: 'BJ', subtitle: 'The Cheapest Trip You Can Take', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Road or short hop', valueFeel: 'Outstanding',
      body: "Cotonou sits right next door: from Lagos it's a road trip through the Seme border, no visa, no flight needed. That makes Benin the cheapest international trip available to a Nigerian passport — often less than a night out in Lekki. Once there, the stilt villages of Ganvié, the history of Ouidah and quiet Atlantic beaches cost very little." },
    { countryName: 'Togo', countryCode: 'TG', subtitle: 'Lomé on a Long Weekend', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Road or short hop', valueFeel: 'Outstanding',
      body: "Continue the coastal road an hour past Cotonou and you're in Lomé, one of West Africa's most relaxed capitals — beaches along the corniche, the Grand Marché, and grilled seafood at naira-friendly prices. Visa-free under ECOWAS, and easily combined with Benin in a single overland trip." },
    { countryName: 'Ghana', countryCode: 'GH', subtitle: 'The Classic, Still Great Value', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Cheap direct flights', valueFeel: 'Outstanding',
      body: "Accra is the obvious first flight abroad for many Nigerians, and it deserves the status: visa-free entry, frequent direct flights from Lagos and Abuja that get genuinely cheap when booked ahead, and a food, music and arts scene that feels both familiar and different. Cape Coast's castles and Kakum's canopy walk round out a week." },
    { countryName: "Côte d'Ivoire", countryCode: 'CI', subtitle: "West Africa's Rising City Break", entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Abidjan has quietly become one of the region's most exciting cities — skyline views over the lagoon, world-class maquis dining, and beach towns like Assinie and historic Grand-Bassam within day-trip range. Slightly pricier than Ghana day-to-day, but still firmly budget territory by global standards." },
    { countryName: 'The Gambia', countryCode: 'GM', subtitle: 'Beach Holiday Without the Visa', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Regional flights', valueFeel: 'Excellent',
      body: 'The Gambia is West Africa\'s dedicated beach-holiday destination: Atlantic sand, river cruises and birdlife, all built around affordable guesthouses. Flights from Nigeria usually route through a regional hub — book the leg early. Daily costs are low, and the tourism infrastructure is used to walk-in budgets.' },
    { countryName: 'Senegal', countryCode: 'SN', subtitle: "Dakar's Culture at ECOWAS Prices", entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: "Dakar delivers big-city culture — Gorée Island's history, thriving music venues, surf beaches at Ngor. Direct flights exist but watch fares; the city itself ranges from cheap street thieboudienne to genuinely upscale, so your budget sets the tone." },
    { countryName: 'Cabo Verde', countryCode: 'CV', subtitle: 'Island Escape, Still ECOWAS', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Regional flights', valueFeel: 'Very good',
      body: "Few travellers realise the Atlantic island nation of Cabo Verde is an ECOWAS member. Sal and Boa Vista offer proper ocean-resort scenery at prices well below comparable islands, and Mindelo is one of Africa's great music towns. Flights from Nigeria route through regional hubs and are the main cost." },
    { countryName: 'Rwanda', countryCode: 'RW', subtitle: 'Visa-Free for African Passports', entryNote: 'Visa-free for Africans', gettingThere: 'Direct flights (Kigali)', valueFeel: 'Excellent',
      body: 'Rwanda opened visa-free entry to citizens of all African countries, and Kigali makes the most compelling case for using it: famously clean streets, serious coffee, the moving Genocide Memorial, and Lake Kivu a scenic drive away. The big-ticket optional extra — gorilla trekking — is where budgets break.' },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari Country, Now Far Easier to Enter', entryNote: 'eTA; fee waived for most Africans', gettingThere: 'Direct flights (Nairobi)', valueFeel: 'Excellent',
      body: "Kenya replaced visas with an electronic travel authorisation (eTA) in 2024, then moved to waive the fee for most African nationals — Nigerians included — with stays of up to about two months. Nairobi's energy, the Maasai Mara, and Diani's beaches; budget safaris make the iconic experience attainable." },
    { countryName: 'Tanzania', countryCode: 'TZ', subtitle: 'Zanzibar and the Serengeti on an eVisa', entryNote: 'eVisa, ~USD 50', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Tanzania asks Nigerians for an eVisa, approximately USD 50 (mid-2026) — apply on the official immigration portal, not lookalike sites. In return: Zanzibar's Stone Town and beaches, Kilimanjaro views, and the Serengeti if the budget allows. Zanzibar's guesthouse scene keeps island costs surprisingly low." },
    { countryName: 'Ethiopia', countryCode: 'ET', subtitle: 'The Convenient eVisa Stopover', entryNote: 'eVisa, ~USD 50–80', gettingThere: 'Direct flights (Addis)', valueFeel: 'Very good',
      body: 'Addis Ababa is Africa\'s great flight hub, which means Ethiopian Airlines fares from Lagos are frequent and competitive — and Ethiopia issues Nigerians a straightforward eVisa via the official portal. The rock-hewn churches of Lalibela and the Simien Mountains are world-class, and daily costs are low.' },
    { countryName: 'São Tomé & Príncipe', countryCode: 'ST', subtitle: "Africa's Quiet Island Secret", entryNote: 'Visa-free short stay', gettingThere: 'Regional flights', valueFeel: 'Very good',
      body: "The two-island nation allows visa-free short stays (commonly up to 15 days) — confirm current terms before booking. It's equatorial-forest-meets-empty-beach territory, with cocoa plantations and almost no crowds. Regional flights (often via Libreville or Accra) are the main cost." },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Free Visa on Arrival, Honestly Budgeted', entryNote: 'Free 30-day visa on arrival', gettingThere: 'Long-haul, one-stop', valueFeel: 'Good',
      body: "The Maldives grants a free 30-day visa on arrival to all nationalities — you'll need proof of accommodation, funds and onward travel. The flight is the big spend. Once there, skip the resorts: guesthouses on local islands like Maafushi turn it into a mid-budget beach trip." },
    { countryName: 'Barbados', countryCode: 'BB', subtitle: 'Visa-Free, With One Big Caveat', entryNote: 'Visa-free (waiver agreement)', gettingThere: 'Long-haul; mind transit visas', valueFeel: 'Good',
      body: 'Nigeria and Barbados operate a visa-waiver arrangement, so Nigerian passport holders can visit visa-free for short stays. The caveat is routing: transiting the UK, USA or Canada generally requires a transit visa for Nigerians, which can quietly kill the budget.' },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Not the Cheapest Visa, But the Easiest Big Trip', entryNote: 'Sponsor-applied visa, ~AED 350+', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Dubai ends the list as the "stretch" pick: the visa is sponsor-applied (via airlines, hotels or licensed agencies), and daily costs are the highest here. But direct flights are plentiful, the process is well-trodden, and free beaches, souks and stopover deals can keep a short trip reasonable.' },
  ],
  '15-cheapest-countries-to-visit-from-bangladesh-in-2026': [
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'Visa on arrival — confirm requirements', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Thailand is a perennial favourite for value — cheap street food, inexpensive transport, and beaches, temples and mountains for every budget.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Malaysia delivers modern cities, rainforests, and island beaches at gentle prices, with Kuala Lumpur an affordable, well-connected hub.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'eVisa or visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Indonesia — Bali especially — is one of the best-value destinations anywhere, with affordable stays, low-cost food, and stunning landscapes.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'The Maldives, once luxury-only, is now accessible via guesthouse stays on local islands — turquoise water without a five-star price.' },
    { countryName: 'Nepal', countryCode: 'NP', subtitle: 'Himalayas Without the Price Tag', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: "Nepal is a budget traveller's dream — the Himalayas, vibrant Kathmandu, and world-class trekking at low cost." },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'A Compact Island, Fully Loaded', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Sri Lanka packs beaches, tea-country hills, ancient cities, and wildlife into a compact, very affordable island.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Vast, Varied, Famously Affordable', entryNote: 'Visa required — confirm process', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'India is vast, varied, and famously affordable, from the Himalayas to tropical beaches, with cheap trains and food.' },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa required — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE offers free beaches, striking architecture, and frequent flight deals as a stopover; with planning, even a luxury-feeling trip is affordable.' },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Turkey is superb value — Istanbul's bazaars, Cappadocia's balloons, and the Aegean coast for less than comparable European trips." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Georgia offers dramatic mountains, ancient wine country, and charming Tbilisi at very low cost, with famous hospitality.' },
    { countryName: 'Azerbaijan', countryCode: 'AZ', subtitle: 'Baku on a Modest Budget', entryNote: 'eVisa (ASAN) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: 'Azerbaijan blends the striking capital Baku with mountains and ancient sites, all at modest prices.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'Outstanding Street-Food Value', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Vietnam offers extraordinary value, from street food and cheap transport to dramatic scenery in Halong Bay and beyond.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Angkor Wat, Very Low Costs', entryNote: 'eVisa or visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Cambodia pairs the awe of Angkor Wat with very low day-to-day costs and a warm welcome.' },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'Kenya brings world-famous safaris, beaches, and vibrant Nairobi, with budget safaris making an iconic African trip attainable.' },
    { countryName: 'Qatar', countryCode: 'QA', subtitle: "Doha's Free Museums, Stopover Deals", entryNote: 'Visa required — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Qatar's Doha offers striking museums, souqs, and waterfronts, with free attractions and stopover deals keeping a short visit affordable." },
  ],
  '15-cheapest-countries-to-visit-from-egypt-in-2026': [
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: "Turkey is superb value — Istanbul's bazaars, Cappadocia's balloons, and the Aegean coast for less than comparable European trips." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Georgia offers dramatic mountains, ancient wine country, and charming Tbilisi at very low cost, with famous hospitality.' },
    { countryName: 'Azerbaijan', countryCode: 'AZ', subtitle: 'Baku on a Modest Budget', entryNote: 'eVisa (ASAN) — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Azerbaijan blends the striking capital Baku with mountains and ancient sites, all at modest prices.' },
    { countryName: 'Jordan', countryCode: 'JO', subtitle: 'Petra and the Dead Sea, Compactly', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Jordan packs Petra, Wadi Rum's deserts, and the Dead Sea into a compact, friendly country at reasonable cost." },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa on arrival — confirm requirements', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'The UAE offers free beaches, striking architecture, and frequent flight deals as a stopover; with planning, even a luxury-feeling trip is affordable.' },
    { countryName: 'Morocco', countryCode: 'MA', subtitle: 'Medinas, Mountains and Riad Stays', entryNote: 'Visa required — confirm process', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: "Morocco's medinas, mountains, and deserts come at gentle prices, with atmospheric riad stays and rich culture." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Kenya brings world-famous safaris, beaches, and vibrant Nairobi, with budget safaris making an iconic African trip attainable.' },
    { countryName: 'Ethiopia', countryCode: 'ET', subtitle: 'Ancient Churches, Dramatic Highlands', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Ethiopia offers ancient churches, dramatic highlands, and a unique culture at low cost — rewarding and affordable.' },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'Visa required — confirm process', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Thailand is a perennial favourite for value — cheap street food, inexpensive transport, and beaches, temples, and mountains for every budget.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: 'Malaysia delivers modern cities, rainforests, and island beaches at gentle prices, with Kuala Lumpur an affordable, well-connected hub.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'eVisa or visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Indonesia — Bali especially — is one of the best-value destinations anywhere, with affordable stays, low-cost food, and stunning landscapes.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'A Compact Island, Fully Loaded', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: 'Sri Lanka packs beaches, tea-country hills, ancient cities, and wildlife into a compact, very affordable island.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Vast, Varied, Famously Affordable', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'India is vast, varied, and famously affordable, from the Himalayas to tropical beaches, with cheap trains and food.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'The Maldives, once luxury-only, is now accessible via guesthouse stays on local islands — turquoise water without a five-star price.' },
    { countryName: 'Qatar', countryCode: 'QA', subtitle: "Doha's Free Museums, Stopover Deals", entryNote: 'Visa-free or visa on arrival — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Qatar's Doha offers striking museums, souqs, and waterfronts, with free attractions and stopover deals keeping a short visit affordable." },
  ],
  '15-cheapest-countries-to-visit-from-ghana-in-2026': [
    { countryName: 'Togo', countryCode: 'TG', subtitle: 'The Easiest Trip You Can Make', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Overland from Accra', valueFeel: 'Outstanding',
      body: "Togo is the easiest international trip a Ghanaian traveller can make. Lomé sits right on the border, a few hours from Accra by STC coach or shared taxi, and the capital's beachfront, markets, and relaxed pace make it a popular weekend escape. Local prices are very low, especially for street food and small guesthouses." },
    { countryName: 'Benin', countryCode: 'BJ', subtitle: 'Ganvié and the Coastal Corridor', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Overland from Accra', valueFeel: 'Outstanding',
      body: 'Continuing east along the coastal corridor, Benin rewards travellers with Ouidah\'s history, the stilt village of Ganvié, and the buzz of Cotonou. You can reach it overland from Accra via Lomé in a single long day of road travel. Daily costs stay very low, and carrying CFA francs makes everything simpler.' },
    { countryName: "Côte d'Ivoire", countryCode: 'CI', subtitle: "Abidjan's Skyline and Lagoons", entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Road or short flight', valueFeel: 'Excellent',
      body: "Abidjan is West Africa's most cosmopolitan city, with a skyline, lagoons, and a food scene worth the trip on its own. It is reachable by road from Accra heading west, or by a quick regional flight if you would rather skip the long drive. Prices run a touch higher than Togo or Benin but still represent strong value." },
    { countryName: 'Senegal', countryCode: 'SN', subtitle: "Dakar's Music and Gorée Island", entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Regional flights', valueFeel: 'Excellent',
      body: 'Dakar is a cultural heavyweight and a major regional flight hub, making Senegal an easy add-on or standalone trip. Expect lively music, Atlantic seafood, and the haunting history of Gorée Island. Costs are low to moderate depending on how you travel.' },
    { countryName: 'The Gambia', countryCode: 'GM', subtitle: 'Compact, Affordable Beach Breaks', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Regional flights', valueFeel: 'Excellent',
      body: 'Tiny, English-speaking, and built around the river that gives it its name, The Gambia is one of West Africa\'s most affordable beach destinations. Your money goes a very long way on guesthouses, fresh fish, and birdwatching trips, and the compact size means little wasted on internal transport.' },
    { countryName: 'Sierra Leone', countryCode: 'SL', subtitle: 'Peninsula Beaches, Few Crowds', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Regional flights', valueFeel: 'Very good',
      body: "Freetown's peninsula beaches are among the most beautiful and least crowded on the continent, and prices on the ground are low. Getting there typically means a regional flight, so factor airfare into the budget, but accommodation and food remain inexpensive once you arrive." },
    { countryName: 'Burkina Faso', countryCode: 'BF', subtitle: 'Sahelian Culture at Low Cost', entryNote: 'Visa-free (ECOWAS) — check travel advisories', gettingThere: 'Regional flights', valueFeel: 'Very good',
      body: 'Burkina Faso offers Sahelian culture, craft markets, and a famously warm welcome at very low daily costs. Security conditions in parts of the country have been volatile, so check your government\'s latest travel advice before planning any route and stay flexible.' },
    { countryName: 'Nigeria', countryCode: 'NG', subtitle: 'Lagos Energy, Budget Prices', entryNote: 'Visa-free (ECOWAS)', gettingThere: 'Overland or short flight', valueFeel: 'Very good',
      body: 'Nigeria is enormous, energetic, and surprisingly affordable once you know where to look. Lagos anchors the eastern end of the Accra–Lomé–Cotonou–Lagos corridor and can be reached overland, though many travellers prefer the short flight. Budget eating and mid-range guesthouses keep costs reasonable.' },
    { countryName: 'Morocco', countryCode: 'MA', subtitle: 'Medinas Without the Long Haul', entryNote: 'Visa required — confirm process', gettingThere: 'Direct flights (Royal Air Maroc)', valueFeel: 'Very good',
      body: "Morocco is where West Africa meets the Mediterranean, and Royal Air Maroc's Accra–Casablanca route makes it an accessible long-haul-feeling trip without the long haul. Marrakech, Fez, and the Atlas Mountains offer value-packed medinas, cheap mint tea, and affordable riads if you avoid peak season." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari on a Range of Budgets', entryNote: 'eTA; fee waived for most Africans', gettingThere: 'Regional flights', valueFeel: 'Very good',
      body: 'Kenya scales to almost any budget, from backpacker hostels in Nairobi to beach guesthouses in Mombasa and Diani. Safari is the headline draw, and while premium lodges are pricey, group tours and public conservancies keep it within reach.' },
    { countryName: 'Rwanda', countryCode: 'RW', subtitle: 'Clean, Safe, Walkable Kigali', entryNote: 'Visa-free for African passports', gettingThere: 'Regional flights', valueFeel: 'Excellent',
      body: 'Kigali is famously clean, safe, and walkable, which makes Rwanda an easy and pleasant trip even for first-time solo travellers. Gorilla trekking is a splurge, but the country also offers lakes, hills, and culture at modest cost.' },
    { countryName: 'Mauritius', countryCode: 'MU', subtitle: 'The One Frank Splurge', entryNote: 'Visa-free — confirm for your passport', gettingThere: 'Long-haul flights', valueFeel: 'Good',
      body: 'Mauritius is the one frank splurge on this list, but it earns its place. Turquoise lagoons, hiking, and a blend of Indian, African, and French cultures make it a standout, and self-catering apartments plus local markets can bring the daily feel down to mid-range.' },
    { countryName: 'Ethiopia', countryCode: 'ET', subtitle: 'Lalibela and Gondar, Cheaply', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights (Addis hub)', valueFeel: 'Excellent',
      body: "Ethiopia delivers some of the continent's most extraordinary history — the rock churches of Lalibela, the castles of Gondar — at remarkably low ground costs. Addis Ababa is a major aviation hub, which can make flights competitive, and food is cheap and excellent." },
    { countryName: 'Egypt', countryCode: 'EG', subtitle: 'Pyramids and the Nile, Affordably', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Egypt pairs world-famous history with genuinely low on-the-ground prices. The pyramids, the Nile, and the temples of Luxor and Aswan can be experienced on a modest budget if you eat locally and use trains and domestic flights wisely.' },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'The Classic Gulf Stopover', entryNote: 'Sponsor-applied visa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE is the classic Gulf value trip for Ghanaian travellers — a popular shopping and stopover destination where free attractions, public beaches, and the metro keep costs down between the glitzier splurges. Budget for the flight and accommodation; the experience itself can be surprisingly affordable.' },
  ],
  '15-cheapest-countries-to-visit-from-india-in-2026': [
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Thailand is superb value, with cheap street food, easy transport, and beaches, temples, and mountains for every budget.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Malaysia pairs modern cities, rainforests, and islands at gentle prices, with Kuala Lumpur a well-connected hub.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Indonesia — Bali especially — offers affordable stays, low-cost food, and stunning landscapes.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'Outstanding Street-Food Value', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Vietnam delivers extraordinary value, from street food to the scenery of Halong Bay.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Angkor Wat, Very Low Costs', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Cambodia pairs Angkor Wat with very low day-to-day costs.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'A Compact Island, Fully Loaded', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Sri Lanka packs beaches, hills, ancient cities, and wildlife into a compact, affordable island.' },
    { countryName: 'Nepal', countryCode: 'NP', subtitle: 'Himalayas Next Door', entryNote: 'Visa-free (open border)', gettingThere: 'Direct flights (short hop)', valueFeel: 'Outstanding',
      body: 'Nepal offers the Himalayas, vibrant Kathmandu, and world-class trekking at low cost.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'The Maldives is accessible via local-island guesthouses — turquoise water without a five-star price.' },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Turkey is excellent value — Istanbul, Cappadocia, and the Aegean coast for less than comparable European trips.' },
    { countryName: 'Azerbaijan', countryCode: 'AZ', subtitle: 'Baku on a Modest Budget', entryNote: 'eVisa (ASAN) — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Azerbaijan blends striking Baku with mountains and ancient sites at modest prices.' },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Georgia offers dramatic mountains, wine country, and charming Tbilisi at very low cost.' },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa required — confirm process', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE offers free beaches, striking architecture, and frequent flight deals.' },
    { countryName: 'Qatar', countryCode: 'QA', subtitle: "Doha's Free Museums, Stopover Deals", entryNote: 'Visa-free or visa on arrival — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Qatar's Doha offers museums, souqs, and waterfronts, with free attractions and stopover deals." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Kenya brings world-famous safaris, beaches, and vibrant Nairobi.' },
    { countryName: 'Egypt', countryCode: 'EG', subtitle: 'Pyramids and the Nile, Affordably', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Egypt offers the pyramids, the Nile, and Red Sea resorts at low cost.' },
  ],
  '15-cheapest-countries-to-visit-from-indonesia-in-2026': [
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: 'The Obvious Starting Point', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Malaysia is the obvious starting point: flights from Jakarta to Kuala Lumpur are some of the cheapest international tickets you will ever see. The food is familiar yet exciting, signage and language overlap with Bahasa, and your rupiah covers comfortable mid-range beds with ease. From KL you can press on overland into Thailand or across to Borneo.' },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Budget Legend Still Delivers', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'The original Southeast Asian budget legend still delivers. Cheap street food, dorms and guesthouses, brilliant transport and a beach for every mood make Thailand a place where a modest daily budget buys a full, fun day. Bangkok is a direct, frequently discounted flight from Jakarta.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'A Coastline Built for Low Spend', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Vietnam packs an extraordinary amount of country into a low daily spend — think bowls of pho for pocket change, sleeper trains and buses linking a 1,600-kilometre coastline, and mid-range rooms that feel like a splurge but barely dent the budget. Hanoi, Hoi An and Ho Chi Minh City each justify the trip on their own.' },
    { countryName: 'Singapore', countryCode: 'SG', subtitle: 'Pricey Beds, Free Sights', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Singapore is the priciest neighbour on this list, but it earns its place because so much of the best stuff is free or cheap: Gardens by the Bay light shows, Marina Bay walks, and world-class hawker centres where a plate costs less than a coffee back home. Treat it as a polished two-or-three-day add-on to a Malaysia trip.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Shoestring Travel Meets Angkor', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Overland or direct flights', valueFeel: 'Outstanding',
      body: 'Cambodia is where shoestring travel and a genuine wonder of the world collide. The temples of Angkor anchor any trip, but the wider country — Phnom Penh, the riverside towns, the sleepy coast — runs on very low daily costs. US dollars circulate widely alongside the local riel, which makes budgeting easy.' },
    { countryName: 'Laos', countryCode: 'LA', subtitle: 'Slow Travel, Gentle Prices', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Overland or connecting flight', valueFeel: 'Outstanding',
      body: "Landlocked, laid-back Laos rewards travellers who slow down. Luang Prabang's temples and night market, the Mekong's long river journeys and the karst landscapes around Vang Vieng all come at gentle, very low prices. It is the quietest of the mainland ASEAN countries and one of the cheapest once you arrive." },
    { countryName: 'Philippines', countryCode: 'PH', subtitle: 'Island-Hopping, English Everywhere', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'For an Indonesian island-lover, the Philippines feels both familiar and fresh: thousands of islands, superb diving and beaches, and widespread English that makes getting around painless. Domestic budget flights and ferries keep island-hopping affordable, and outside the resort enclaves daily costs stay low.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'Beaches, Hills and Trains for Little', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Sri Lanka is one of the best-value trips within easy reach of Indonesia. A small island packs in beaches, tea-country hills, ancient cities and wildlife safaris, all linked by famously cheap and gloriously scenic trains. Guesthouse stays, rice-and-curry feasts and tuk-tuk rides keep the daily spend genuinely low.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Vast, Varied, Famously Cheap', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: "Few countries stretch a budget like India. From Rajasthan's forts to Kerala's backwaters and the Himalayan foothills, the variety is endless and the on-the-ground costs are among the lowest anywhere — cheap thalis, cheap trains, cheap beds. It rewards travellers who give it time and patience." },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Bucket-List Sights, Fair Prices', entryNote: 'eVisa — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: "Turkey is the long-haul value pick that still punches above its price. Istanbul's mosques and bazaars, Cappadocia's balloons and the Aegean coast deliver bucket-list moments without European price tags, and meals, transport and mid-range stays feel like a bargain." },
    { countryName: 'Hong Kong', countryCode: 'HK', subtitle: 'Free Skyline, Costly Beds', entryNote: 'Visa-free — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Hong Kong, like Singapore, has expensive hotels but a surprising amount of free spectacle: the Victoria Harbour skyline, the Peak walks, buzzing street markets and some of the world's best cheap dim sum and noodle joints. The Octopus card makes its superb transit effortless." },
    { countryName: 'Timor-Leste', countryCode: 'TL', subtitle: 'Off-Grid, Right Next Door', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Overland or short flight', valueFeel: 'Very good',
      body: "For the adventurous, Timor-Leste is one of the region's last genuinely untouristed frontiers — and it is right on Indonesia's doorstep, reachable overland from West Timor or on a short flight. Expect raw landscapes, world-class diving off Atauro Island and very few other visitors." },
    { countryName: 'Brunei', countryCode: 'BN', subtitle: 'Calm, Clean, Close to Borneo', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Short hop from Borneo', valueFeel: 'Very good',
      body: 'Tiny, tidy and calm, Brunei makes an easy, good-value stop if you are already exploring Borneo. The opulent mosques, the stilt-village water world of Kampong Ayer and the pristine rainforest of Ulu Temburong are the draws, and a short hop from Sabah or Sarawak keeps flights cheap.' },
    { countryName: 'Nepal', countryCode: 'NP', subtitle: 'Adventure-Per-Dollar Champion', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Nepal offers arguably the best adventure-per-dollar on the planet. Teahouse trekking in the Annapurna or Everest regions, the temples and chaos of Kathmandu, and lakeside Pokhara all come at very low daily costs, with guides and porters affordable too.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Paradise, Minus the Resort Price', entryNote: 'Free visa on arrival', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'The Maldives no longer means a five-figure honeymoon. By staying on local inhabited islands rather than private resorts, budget travellers get the same turquoise water, snorkelling and sandbanks for a fraction of the price, eating at local cafés and taking public ferries between atolls.' },
  ],
  '15-cheapest-countries-to-visit-from-kenya-in-2026': [
    { countryName: 'Tanzania', countryCode: 'TZ', subtitle: 'The Natural First Trip', entryNote: 'Visa-free (East African Community)', gettingThere: 'Overland from Nairobi', valueFeel: 'Outstanding',
      body: "Tanzania is the natural first trip for many Kenyans because you can reach it overland — buses run from Nairobi to Arusha and Moshi, and the shared East African Community market keeps prices feeling reasonable. From there, the northern safari circuit, Zanzibar's beaches and Kilimanjaro are all within reach. Daily costs for food, local transport and guesthouses are low." },
    { countryName: 'Uganda', countryCode: 'UG', subtitle: 'The Pearl of Africa, Overland', entryNote: 'Visa-free (East African Community)', gettingThere: 'Overland from Nairobi', valueFeel: 'Outstanding',
      body: 'The Pearl of Africa is one of the easiest overland escapes from Nairobi, with through-buses running to Kampala. Once you arrive, Uganda is genuinely cheap — street food, boda transport and budget lodgings cost little, and the landscapes around Lake Victoria, Jinja and the western parks are spectacular. Gorilla permits are the one big-ticket exception.' },
    { countryName: 'Rwanda', countryCode: 'RW', subtitle: 'Compact, Clean, Easy Regional Hop', entryNote: 'Visa-free (East African Community)', gettingThere: 'Regional flights or overland', valueFeel: 'Excellent',
      body: 'Rwanda is compact, orderly and easy to navigate, which makes it a low-stress regional hop. Kigali is walkable and safe-feeling, and buses connect it to the rest of the region. Everyday spending stays modest, though premium experiences like gorilla permits sit at the high end.' },
    { countryName: 'Ethiopia', countryCode: 'ET', subtitle: 'A Short Flight, a Distinctive Culture', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights (short hop)', valueFeel: 'Excellent',
      body: "A short flight north lands you in one of Africa's most distinctive cultures, with rock-hewn churches, highland scenery and a coffee tradition that started it all. Local prices are low once you are on the ground, so food, buses and simple guesthouses keep daily costs down." },
    { countryName: 'South Africa', countryCode: 'ZA', subtitle: 'A Big Trip Feeling, Modest Price', entryNote: 'Visa-free — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'South Africa offers some of the best value per shilling for a "big trip" feeling — Cape Town, the Garden Route, Kruger and Johannesburg deliver world-class experiences at prices that often undercut comparable destinations elsewhere. Self-catering, public markets and self-drive safaris keep budgets sensible.' },
    { countryName: 'Mauritius', countryCode: 'MU', subtitle: 'Island Time, Off-Peak', entryNote: 'Visa-free — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Mauritius has a reputation as a honeymoon splurge, but off-peak and with a little planning it is more attainable than it looks. Self-catering apartments, local markets and public beaches cut the cost dramatically versus all-inclusive resorts.' },
    { countryName: 'Zimbabwe', countryCode: 'ZW', subtitle: 'The Budget Gateway to Victoria Falls', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Zimbabwe is the budget gateway to Victoria Falls, one of the continent's great sights, and local prices for food and lodging are low. Beyond the falls, Hwange offers excellent wildlife with fewer crowds and lower costs than marquee parks elsewhere." },
    { countryName: 'Zambia', countryCode: 'ZM', subtitle: 'Safari Without the Markup', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Zambia delivers serious safari and the other half of Victoria Falls without the premium price tag attached to some neighbours. Walking safaris in South Luangwa are a bucket-list experience, and self-drive or budget camping options keep costs down.' },
    { countryName: 'Botswana', countryCode: 'BW', subtitle: 'Premium Wildlife, Budget Self-Drive', entryNote: 'Visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'Botswana is famous for high-end wildlife — the Okavango Delta and Chobe are legendary — but it does not have to bankrupt you. Self-drive camping, mobile safaris and shoulder-season timing bring costs into reach, and the wildlife density is hard to beat anywhere.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: 'Long-Haul Value, Cheap Street Food', entryNote: 'eVisa — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: 'Malaysia is where long-haul value really shows: Kuala Lumpur is modern and affordable, street food is cheap and delicious, and the islands and rainforests cost little once you arrive. It works well as a base for exploring Southeast Asia.' },
    { countryName: 'Singapore', countryCode: 'SG', subtitle: 'Costly Base, Free Things Stretch It', entryNote: 'eVisa — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Good',
      body: "Singapore is undeniably an expensive base, but its value lies in how much you can do for free or cheap — hawker centres serve some of the world's best low-cost food, and the gardens, neighbourhoods and waterfront cost nothing to wander." },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'Famous Value for Every Budget', entryNote: 'eVisa — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: "Thailand earns its budget-travel fame honestly. From Bangkok's markets to northern Chiang Mai and the southern beaches, daily costs for food, transport and accommodation are low, and the tourism infrastructure makes everything easy." },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'The Popular Stopover Getaway', entryNote: 'Visa on arrival — confirm requirements', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE — Dubai and Abu Dhabi especially — is a hugely popular getaway and stopover for Kenyan travellers, thanks to frequent flights and the chance to combine it with onward journeys. Free beaches, public transport and self-catering can keep a short visit reasonable.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali and Beyond on Little Money', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: 'Indonesia, and Bali in particular, remains a byword for affordable tropical travel. Guesthouses, warungs and scooter rentals cost little, and beyond Bali the archipelago offers volcanoes, reefs and culture across thousands of islands.' },
    { countryName: 'Seychelles', countryCode: 'SC', subtitle: 'Splurge Islands, Doable Self-Catering', entryNote: 'Visa-free on arrival (all nationalities)', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Seychelles is the splurge of this list, but it is more doable than its luxury image suggests. Self-catering guesthouses, public buses and the islands' free, stunning beaches let independent travellers sidestep resort prices." },
  ],
  '15-cheapest-countries-to-visit-from-nepal-in-2026': [
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Thailand is a perennial favourite for value — cheap, delicious street food, inexpensive transport, and beaches, temples, and mountains to suit every budget. Bangkok, Chiang Mai, and the southern islands offer world-class experiences at a fraction of Western prices.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Malaysia delivers modern cities, rainforests, and island beaches at gentle prices. Kuala Lumpur is an affordable, well-connected hub, and food across the country is both excellent and cheap.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Indonesia — and Bali in particular — is one of the best-value destinations anywhere, with affordable villas, low-cost food, and a wealth of beaches, temples, and rice-terrace landscapes.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'Outstanding Street-Food Value', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Vietnam offers extraordinary value, from street food and cheap local transport to dramatic scenery in Halong Bay and the highlands. Cities like Hanoi and Ho Chi Minh City are affordable, vibrant, and rich in history.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Angkor Wat, Very Low Costs', entryNote: 'eVisa or visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Cambodia pairs the awe of Angkor Wat with low day-to-day costs. Food, guesthouses, and local transport are inexpensive, and the warm welcome makes it an easy, rewarding budget destination.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Vast, Varied, Famously Affordable', entryNote: 'Visa-free (open border)', gettingThere: 'Direct flights (short hop)', valueFeel: 'Outstanding',
      body: 'India is vast, varied, and famously affordable, from the Himalayas to tropical beaches. Trains and local food cost little, and a modest budget stretches a long way across its many regions and cultures.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: 'The Maldives is best known for luxury, but guesthouse stays on local islands have made it surprisingly accessible — turquoise water and white sand without a five-star price tag, especially outside peak season.' },
    { countryName: 'Azerbaijan', countryCode: 'AZ', subtitle: 'Baku on a Modest Budget', entryNote: 'eVisa (ASAN) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Azerbaijan blends a striking modern capital, Baku, with mountains and ancient sites, all at modest prices. It's an increasingly popular, good-value gateway between Europe and Asia." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Georgia offers dramatic mountains, ancient wine country, and the charming capital Tbilisi at very low cost. Generous hospitality and affordable food and lodging make it a standout value destination.' },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Turkey is superb value, especially with a favourable exchange rate — Istanbul's bazaars and mosques, Cappadocia's balloons, and the Aegean coast all cost less than comparable European trips." },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa required — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE — Dubai and Abu Dhabi — is pricier than some neighbours but offers free beaches, striking architecture, and frequent flight deals as a stopover. With planning, even a luxury-feeling trip can be done affordably.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'A Compact Island, Fully Loaded', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Sri Lanka packs beaches, tea-country hills, ancient cities, and wildlife into a compact, very affordable island. Local food and transport are cheap, and it's an easy place to travel comfortably on a small budget." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'Kenya brings world-famous safaris, beaches, and vibrant Nairobi. While top lodges are costly, budget safaris and coastal stays make an iconic African trip more affordable than many assume.' },
    { countryName: 'Singapore', countryCode: 'SG', subtitle: 'Free Gardens, Hawker-Centre Prices', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Singapore is more expensive than its neighbours, but free gardens, hawker-centre food, and efficient transport let budget travellers enjoy this gleaming city-state without overspending.' },
  ],
  '15-cheapest-countries-to-visit-from-pakistan-in-2026': [
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'Visa required — confirm process', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Superb value with cheap street food, easy transport, and a spread of beaches, temples, and mountains for every budget. Bangkok, Chiang Mai, and the southern islands can each be done cheaply or lavishly.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Modern cities, rainforests, and islands at gentle prices, with Kuala Lumpur a well-connected, low-cost hub that pairs neatly with a wider Southeast Asia trip.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'Visa required — confirm process', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Bali especially offers affordable guesthouses, low-cost food, and stunning landscapes — and beyond Bali, the value only deepens.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Once a honeymoon splurge, now accessible via local-island guesthouses — turquoise water and reefs without a five-star price tag.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'A Compact Island, Fully Loaded', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Beaches, hill country, ancient cities, and wildlife packed into one compact, very affordable island that's quick to reach from Pakistan." },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Excellent value straddling Europe and Asia — Istanbul, Cappadocia, and the Aegean coast for far less than comparable European trips.' },
    { countryName: 'Azerbaijan', countryCode: 'AZ', subtitle: 'Baku on a Modest Budget', entryNote: 'eVisa (ASAN) — confirm cost', gettingThere: 'Direct flights (short hop)', valueFeel: 'Very good',
      body: 'Striking Baku blends with mountains and ancient sites at modest prices, and flights are short.' },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Dramatic mountains, wine country, and charming Tbilisi at some of the lowest day-to-day costs on this list.' },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa required — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Free public beaches, striking architecture, and frequent flight deals make the UAE cheaper than its glossy reputation suggests — especially in the warmer months.' },
    { countryName: 'Qatar', countryCode: 'QA', subtitle: "Doha's Free Museums, Stopover Deals", entryNote: 'Visa required — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Doha's museums, souqs, and waterfronts include plenty of free attractions, and stopover deals make it cheap to combine with onward travel." },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'Outstanding Street-Food Value', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Extraordinary value, from world-class street food to the scenery of Halong Bay and the cities of the north and south.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Angkor Wat, Very Low Costs', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Angkor Wat paired with very low day-to-day costs makes Cambodia one of the best-value bucket-list destinations anywhere.' },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'World-famous safaris, Indian Ocean beaches, and vibrant Nairobi — book the shoulder season for the best balance of wildlife and price.' },
    { countryName: 'Egypt', countryCode: 'EG', subtitle: 'Pyramids and the Nile, Affordably', entryNote: 'Visa required — confirm process', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'The pyramids, the Nile, and Red Sea resorts at consistently low cost, with a long season that suits flexible budgets.' },
    { countryName: 'Nepal', countryCode: 'NP', subtitle: 'Himalayas Without the Price Tag', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'The Himalayas, vibrant Kathmandu, and world-class trekking at low cost — unbeatable for travellers who want big landscapes on a small budget.' },
  ],
  '15-cheapest-countries-to-visit-from-philippines-in-2026': [
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Thailand is a perennial favourite for value — cheap street food, inexpensive transport, and beaches, temples, and mountains for every budget.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Malaysia delivers modern cities, rainforests, and island beaches at gentle prices, with Kuala Lumpur an affordable, well-connected hub.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Indonesia — Bali especially — is one of the best-value destinations anywhere, with affordable stays, low-cost food, and stunning landscapes.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'Outstanding Street-Food Value', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Vietnam offers extraordinary value, from street food and cheap transport to dramatic scenery in Halong Bay and beyond.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Angkor Wat, Very Low Costs', entryNote: 'Visa-free (ASEAN)', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Cambodia pairs the awe of Angkor Wat with very low day-to-day costs and a warm welcome.' },
    { countryName: 'Singapore', countryCode: 'SG', subtitle: 'Free Gardens, Hawker-Centre Prices', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Singapore is pricier than its neighbours, but free gardens, hawker-centre food, and efficient transport keep it enjoyable on a budget.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Vast, Varied, Famously Affordable', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'India is vast, varied, and famously affordable, from the Himalayas to tropical beaches, with cheap trains and food.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'A Compact Island, Fully Loaded', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Sri Lanka packs beaches, tea-country hills, ancient cities, and wildlife into a compact, very affordable island.' },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa on arrival — confirm requirements', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE offers free beaches, striking architecture, and frequent flight deals as a stopover; with planning, even a luxury-feeling trip is affordable.' },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Turkey is superb value — Istanbul's bazaars, Cappadocia's balloons, and the Aegean coast for less than comparable European trips." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Georgia offers dramatic mountains, ancient wine country, and charming Tbilisi at very low cost, with famous hospitality.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'The Maldives, once luxury-only, is now accessible via guesthouse stays on local islands — turquoise water without a five-star price.' },
    { countryName: 'Qatar', countryCode: 'QA', subtitle: "Doha's Free Museums, Stopover Deals", entryNote: 'Visa-free or visa on arrival — confirm for your passport', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Qatar's Doha offers striking museums, souqs, and waterfronts, with free attractions and stopover deals keeping a short visit affordable." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'Kenya brings world-famous safaris, beaches, and vibrant Nairobi, with budget safaris making an iconic African trip attainable.' },
    { countryName: 'Morocco', countryCode: 'MA', subtitle: 'Medinas, Mountains and Riad Stays', entryNote: 'Visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Morocco's medinas, mountains, and deserts come at gentle prices, with atmospheric riad stays and rich culture." },
  ],
  '15-cheapest-countries-to-visit-from-sri-lanka-in-2026': [
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Street-Food Value Champion', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Thailand is a perennial favourite for value — cheap, delicious street food, inexpensive transport, and beaches, temples, and mountains to suit every budget. Bangkok, Chiang Mai, and the southern islands offer world-class experiences at a fraction of Western prices.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: "KL's Easy, Affordable Hub", entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'Malaysia delivers modern cities, rainforests, and island beaches at gentle prices. Kuala Lumpur is an affordable, well-connected hub, and food across the country is both excellent and cheap.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali on a Guesthouse Budget', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Indonesia — and Bali in particular — is one of the best-value destinations anywhere, with affordable villas, low-cost food, and a wealth of beaches, temples, and rice-terrace landscapes.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'Outstanding Street-Food Value', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Vietnam offers extraordinary value, from street food and cheap local transport to dramatic scenery in Halong Bay and the highlands. Cities like Hanoi and Ho Chi Minh City are affordable, vibrant, and rich in history.' },
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'Angkor Wat, Very Low Costs', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Cambodia pairs the awe of Angkor Wat with low day-to-day costs. Food, guesthouses, and local transport are inexpensive, and the warm welcome makes it an easy, rewarding budget destination.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Vast, Varied, Famously Affordable', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: 'India is vast, varied, and famously affordable, from the Himalayas to tropical beaches. Trains and local food cost little, and a modest budget stretches a long way across its many regions and cultures.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Turquoise Water, Guesthouse Prices', entryNote: 'Free visa on arrival', gettingThere: 'Direct flights (short hop)', valueFeel: 'Very good',
      body: 'The Maldives is best known for luxury, but guesthouse stays on local islands have made it surprisingly accessible — turquoise water and white sand without a five-star price tag, especially outside peak season.' },
    { countryName: 'Azerbaijan', countryCode: 'AZ', subtitle: 'Baku on a Modest Budget', entryNote: 'eVisa (ASAN) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Azerbaijan blends a striking modern capital, Baku, with mountains and ancient sites, all at modest prices. It's an increasingly popular, good-value gateway between Europe and Asia." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Dramatic Scenery, Rock-Bottom Prices', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Georgia offers dramatic mountains, ancient wine country, and the charming capital Tbilisi at very low cost. Generous hospitality and affordable food and lodging make it a standout value destination.' },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Lite at a Fraction of the Price', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: "Turkey is superb value, especially with a favourable exchange rate — Istanbul's bazaars and mosques, Cappadocia's balloons, and the Aegean coast all cost less than comparable European trips." },
    { countryName: 'United Arab Emirates', countryCode: 'AE', subtitle: 'Free Beaches, Frequent Flight Deals', entryNote: 'Visa required — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The UAE — Dubai and Abu Dhabi — is pricier than some neighbours but offers free beaches, striking architecture, and frequent flight deals as a stopover. With planning, even a luxury-feeling trip can be done affordably.' },
    { countryName: 'Nepal', countryCode: 'NP', subtitle: "A Budget Traveller's Dream", entryNote: 'Visa on arrival — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Nepal is a budget traveller's dream — the Himalayas, vibrant Kathmandu, and some of the world's great trekking, all at low cost. Guesthouses and local food are inexpensive, and the scenery is priceless." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari and Beaches, Off-Peak Value', entryNote: 'eTA — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Kenya brings world-famous safaris, beaches, and vibrant Nairobi. While top lodges are costly, budget safaris and coastal stays make an iconic African trip more affordable than many assume.' },
    { countryName: 'Singapore', countryCode: 'SG', subtitle: 'Free Gardens, Hawker-Centre Prices', entryNote: 'eVisa — confirm cost', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'Singapore is more expensive than its neighbours, but free gardens, hawker-centre food, and efficient transport let budget travellers enjoy this gleaming city-state without overspending.' },
  ],
  '15-cheapest-countries-to-visit-from-vietnam-in-2026': [
    { countryName: 'Cambodia', countryCode: 'KH', subtitle: 'The Natural First Stop', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Overland from Ho Chi Minh City', valueFeel: 'Outstanding',
      body: 'Cambodia is the natural first stop for a Vietnamese budget trip because you can reach it overland. Sleeper buses from Ho Chi Minh City roll through the Bavet–Moc Bai border to Phnom Penh for the price of a nice dinner, and guesthouses, street food and tuk-tuks cost very little once inside. Angkor Wat, riverside Phnom Penh and the southern coast all fit a tight budget.' },
    { countryName: 'Laos', countryCode: 'LA', subtitle: 'Slow Rivers, Tiny Daily Spend', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Overland from Vietnam', valueFeel: 'Outstanding',
      body: 'Laos rewards slow, cheap travel more than almost anywhere in the region. Overland crossings from northern and central Vietnam connect to Luang Prabang and Vientiane, and the famous two-day Mekong slow boat is a bargain way to drift across the country. Daily spending on food, local buses and simple riverside rooms stays remarkably low.' },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Backbone of Budget Southeast Asia', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Thailand is the backbone of budget Southeast Asia and easy to reach from Vietnam on frequent low-cost flights into Bangkok. Once there, street food costs almost nothing, intercity buses and trains are cheap, and competition keeps hostels and guesthouses affordable from the islands to Chiang Mai.' },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: 'A Comfortable, Organised Value Trip', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Malaysia delivers strong value with a comfortable, organised feel. AirAsia and other carriers run cheap routes from Vietnam into Kuala Lumpur, where hawker food, modern public transport and a mix of cultures give you a lot for very little. Penang in particular is a budget traveller\'s dream for its street food alone.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Enormous, and Genuinely Affordable', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Indonesia is enormous and genuinely affordable once you arrive. Direct and connecting flights reach Bali and Jakarta from Vietnam\'s main airports, and beyond the obvious beaches, your money stretches a long way across food, scooter rentals and simple homestays.' },
    { countryName: 'Philippines', countryCode: 'PH', subtitle: 'A Modest Budget, Serious Island Time', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'The Philippines turns a modest budget into serious island time. Low-cost flights link Vietnam to Manila and Cebu, and from there a network of cheap domestic flights and ferries opens up Palawan, Bohol and beyond. Food, local transport and basic beach lodging are inexpensive.' },
    { countryName: 'Singapore', countryCode: 'SG', subtitle: 'Priciest Beds, Free Best Experiences', entryNote: 'Visa-free (ASEAN)', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: "Singapore is the priciest place on this list, but it earns its spot because clever travellers visit cheaply. Beds cost more, yet the city's best experiences — Gardens by the Bay's outdoor zones, Marina Bay at night, museums and parks — are free or near-free, and hawker centres serve world-class meals for a few dollars." },
    { countryName: 'Myanmar', countryCode: 'MM', subtitle: 'Some of the Region\'s Lowest Prices', entryNote: 'Visa-free (ASEAN) — check current advisories', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Myanmar offers some of the lowest day-to-day prices anywhere in Southeast Asia, with simple guesthouses, cheap local food and inexpensive overland transport between Yangon, Mandalay and Bagan. Travel here requires extra preparation and a careful read of current conditions.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'Huge Variety, Small Affordable Island', entryNote: 'eVisa (ETA) — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: 'Sri Lanka packs huge variety into a small, affordable island. Connecting flights from Vietnam reach Colombo, and once there the iconic hill-country trains, cheap homestays and low food costs make it one of South Asia\'s best-value destinations.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'A Low Daily Budget, Travelled Like a Local', entryNote: 'eVisa — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: "India is the definition of a low daily budget if you travel like a local. Flights from Vietnam connect through regional hubs, and once inside the country, trains, street food and guesthouses cost very little for the sheer scale of what you can see — from Rajasthan's forts to Kerala's backwaters." },
    { countryName: 'Nepal', countryCode: 'NP', subtitle: 'A Budget Traveller\'s Classic', entryNote: 'Visa on arrival — confirm cost', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: 'Nepal is a budget traveller\'s classic, where Himalayan scenery comes at very low day-to-day cost. Connecting flights reach Kathmandu, and from there teahouse trekking, cheap local food and inexpensive guesthouses keep spending down even on multi-week itineraries.' },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Quietly Reachable on a Budget', entryNote: 'Free visa on arrival', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'The Maldives has quietly become reachable on a budget thanks to local-island guesthouses rather than private-island resorts. Connecting flights from Vietnam land in Malé, and public ferries or shared speedboats take you to inhabited islands where rooms, local meals and snorkelling trips cost a fraction of the resort price.' },
    { countryName: 'Kyrgyzstan', countryCode: 'KG', subtitle: 'The Emerging Central Asia Bargain', entryNote: 'eVisa or visa-free — confirm for your passport', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: 'Kyrgyzstan is the emerging-bargain wildcard on this list and a genuinely different experience for Vietnamese travellers used to Southeast Asia. Reached via connecting flights into Bishkek, it offers dramatic mountains, alpine lakes and yurt stays at low daily costs once you arrive.' },
    { countryName: 'China', countryCode: 'CN', subtitle: 'Neighbouring Provinces, Cheap Rail', entryNote: 'Visa required — confirm process', gettingThere: 'Overland or short flight', valueFeel: 'Good',
      body: "China's provinces neighbouring Vietnam — Yunnan and Guangxi especially — are surprisingly affordable and easy to fold into an overland or short-flight trip. Cheap and astonishingly fast rail moves you between cities for less than you might expect." },
    { countryName: 'Brunei', countryCode: 'BN', subtitle: 'Small but Inexpensive Day-to-Day', entryNote: 'Visa-free (ASEAN)', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: 'Brunei is small and often overlooked, but day-to-day costs for food and local transport are modest, and it slots neatly into a wider Borneo itinerary alongside Malaysia. Connecting flights reach Bandar Seri Begawan, where mosques, water-village boat trips and rainforest reserves fill a short, inexpensive stop.' },
  ],
  'cheapest-countries-to-visit-from-the-usa-2026': [
    { countryName: 'Mexico', countryCode: 'MX', subtitle: 'The Default Answer for a Reason', entryNote: 'Visa-free', gettingThere: 'Direct flights', valueFeel: 'Outstanding',
      body: "The default answer for a reason. Flights from almost every US city are cheap and frequent, US dollars stretch far outside the resort zones, and Americans enter visa-free for tourism. Skip Cancún's resort strip for Oaxaca, Mérida or Mexico City and your daily budget drops dramatically while the food gets better." },
    { countryName: 'Guatemala', countryCode: 'GT', subtitle: "Central America's Best-Kept Secret", entryNote: 'Visa-free', gettingThere: 'Direct flights (via US hub)', valueFeel: 'Outstanding',
      body: "Central America's best-kept budget secret. Antigua's colonial streets, Lake Atitlán's volcanoes and Tikal's ruins cost a fraction of pricier neighbours. Entry is visa-free for US citizens for short tourism, and guesthouses and local comedores keep daily spending very low." },
    { countryName: 'Colombia', countryCode: 'CO', subtitle: 'Big-City Energy, Small-City Prices', entryNote: 'Visa-free', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Medellín and Bogotá offer big-city energy at small-city prices, with the Caribbean coast and coffee region within easy reach. Americans visit visa-free for tourism, and direct flights from Miami, Houston and other hubs are short and often cheap.' },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: "Southeast Asia's Value Champion", entryNote: 'eVisa — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Excellent',
      body: "Southeast Asia's value champion. Street food for pocket change, comfortable rooms for very little, and staggering scenery from Ha Long Bay to the Mekong. US citizens typically need an eVisa arranged online in advance — easy, but don't skip it." },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'The Template for Cheap, Easy Travel', entryNote: 'Visa-free', gettingThere: 'Long-haul flights', valueFeel: 'Excellent',
      body: 'The template for cheap, easy travel. Americans get visa-free entry for short tourism, English is widely used, and the tourism infrastructure is superb. Bangkok, Chiang Mai and the islands each offer a different flavour of low-cost travel.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Beyond Bali, the Value Deepens', entryNote: 'Visa on arrival', gettingThere: 'Long-haul flights', valueFeel: 'Excellent',
      body: "Bali gets the headlines, but Indonesia's real value is in Java, Lombok and beyond. Entry is usually via a visa-on-arrival for US citizens for short tourism — quick to sort at the airport. Food, transport and accommodation are inexpensive." },
    { countryName: 'Philippines', countryCode: 'PH', subtitle: 'Island-Hopping Without Blowing the Budget', entryNote: 'Visa-free', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: 'Thousands of islands, warm English-speaking hospitality, and prices that make a beach trip genuinely affordable. Americans typically enter visa-free for short tourism, and the internal flights and ferries between islands are cheap.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Astonishing Value and Variety', entryNote: 'eVisa — confirm cost', gettingThere: 'Long-haul flights', valueFeel: 'Outstanding',
      body: "Astonishing value and variety — from the Himalayas to Kerala's backwaters — at some of the lowest daily costs anywhere. US citizens need an eVisa, applied for online before travel. Once inside, trains, food and guesthouses cost very little." },
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'The Bridge Between Europe and Asia', entryNote: 'eVisa or visa-free — confirm current rule', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'The bridge between Europe and Asia, and a value standout thanks to a favourable exchange rate. Istanbul, Cappadocia and the Mediterranean coast deliver a lot for the money.' },
    { countryName: 'Portugal', countryCode: 'PT', subtitle: 'The Most Affordable Western Europe', entryNote: 'Visa-free (Schengen 90/180)', gettingThere: 'Direct flights', valueFeel: 'Good',
      body: 'The most affordable Western European country, and proof this list is not only developing nations. Lisbon, Porto and the Algarve cost noticeably less than France or Italy. Americans enter visa-free under the Schengen 90/180 rule.' },
    { countryName: 'Albania', countryCode: 'AL', subtitle: "The Balkans' Rising Value Star", entryNote: 'Visa-free', gettingThere: 'One-stop flights (via Europe)', valueFeel: 'Excellent',
      body: "The Balkans' rising value star. A stunning Adriatic coastline at a fraction of Croatia's prices, plus mountains and Ottoman-era towns inland. Americans enjoy generous visa-free access, and daily costs are among the lowest in Europe." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'One of the Best-Value Places on Earth', entryNote: 'Visa-free (generous stay)', gettingThere: 'One-stop flights', valueFeel: 'Outstanding',
      body: "The country, not the state — and one of the best-value destinations on Earth right now. Tbilisi's food and wine scene is remarkable and cheap, the Caucasus mountains are jaw-dropping, and US citizens get exceptionally generous visa-free stays." },
    { countryName: 'Morocco', countryCode: 'MA', subtitle: 'North Africa, Within Easy Reach', entryNote: 'Visa-free', gettingThere: 'One-stop flights (via Europe)', valueFeel: 'Very good',
      body: "North Africa within easy reach of Europe. Marrakech's souks, the Sahara and the coast offer huge contrast at low cost. US citizens enjoy visa-free short stays, and riads and local food keep budgets down." },
    { countryName: 'Bolivia', countryCode: 'BO', subtitle: "South America's Cheapest Country", entryNote: 'Visa required — confirm current rule', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: "South America's cheapest country to travel, with the surreal Uyuni salt flats, the Andes and the Amazon. Daily costs are rock-bottom. Entry rules for US citizens have varied, so confirm the current requirement carefully." },
    { countryName: 'Peru', countryCode: 'PE', subtitle: 'More Than One Ruin', entryNote: 'Visa-free', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: "Machu Picchu anchors a trip, but Peru's food scene, Amazon and Pacific coast make it far more than one ruin. Americans enter visa-free for tourism, and outside the Inca Trail's fixed costs, daily spending is low." },
  ],
  'cheapest-countries-to-visit-from-the-uk-2026': [
    { countryName: 'Turkey', countryCode: 'TR', subtitle: 'Europe-Meets-Asia on a Budget', entryNote: 'Visa-free short stay', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Turkey is arguably the best all-round value trip from Britain. Flights to Istanbul, Antalya and Dalaman are plentiful and cheap, the lira works firmly in your favour, and a rich mezze dinner costs a fraction of the London equivalent. Istanbul alone justifies the trip.' },
    { countryName: 'Portugal', countryCode: 'PT', subtitle: 'The Cheapest Western Europe Gets', entryNote: 'Visa-free, 90/180', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: "Within the euro zone, Portugal is the standout for value. Budget flights to Lisbon, Porto and Faro are cheap and frequent, and once you're there, pastéis de nata, grilled fish and vinho verde cost little. The Algarve rivals pricier Med resorts for a lot less." },
    { countryName: 'Albania', countryCode: 'AL', subtitle: "Europe's Best-Value Coast", entryNote: 'Visa-free short stay', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Albania has quietly become the continent\'s value darling, and deservedly so. The Albanian Riviera offers Ionian beaches to rival Greece and Croatia at a fraction of the price, and cities like Tirana and Berat are cheap, characterful and safe.' },
    { countryName: 'Bulgaria', countryCode: 'BG', subtitle: 'Ski and Sea for Less', entryNote: 'Visa-free, 90/180', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Bulgaria delivers remarkable range on a small budget: Black Sea beaches in summer, some of Europe's cheapest skiing in winter, and Sofia and Plovdiv for culture year-round. Flights are inexpensive and daily costs are among the lowest in the EU." },
    { countryName: 'Georgia', countryCode: 'GE', subtitle: 'Wine, Mountains and Bargains', entryNote: 'Visa-free short stay', gettingThere: 'One-stop flights', valueFeel: 'Excellent',
      body: "Georgia punches far above its price. Tbilisi's old town, the Caucasus mountains and the world's oldest wine tradition come at genuinely low daily costs, and it sits outside Schengen. Britons typically enjoy a long visa-free stay here." },
    { countryName: 'Morocco', countryCode: 'MA', subtitle: 'Close, Cheap and Exotic', entryNote: 'Visa-free short stay', gettingThere: 'Direct flights', valueFeel: 'Very good',
      body: 'Just a short hop from the UK, Morocco offers medinas, mountains, desert and coast with daily costs well below European levels. Marrakesh, Fez and the Atlas make for an intense, affordable week, and riads deliver atmosphere on a budget.' },
    { countryName: 'Egypt', countryCode: 'EG', subtitle: 'Ancient Wonders, Modern Value', entryNote: 'Visa-on-arrival / eVisa', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "With the Egyptian pound weak against sterling, Egypt is exceptional value in 2026. The Pyramids, Luxor's temples and Red Sea diving at Dahab and Sharm cost a fraction of comparable experiences elsewhere." },
    { countryName: 'Vietnam', countryCode: 'VN', subtitle: 'The Long-Haul Value Champion', entryNote: 'eVisa', gettingThere: 'Long-haul flights', valueFeel: 'Outstanding',
      body: "If you're flying long-haul, Vietnam offers perhaps the best pound-for-pound value anywhere. Street-food bowls for a pound or two, cheap comfortable buses and trains, and landscapes from Ha Long Bay to the Mekong." },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: 'Backpacker Icon, Still a Bargain', entryNote: 'Visa-free short stay', gettingThere: 'Long-haul flights', valueFeel: 'Outstanding',
      body: "Thailand remains the benchmark for cheap, high-quality long-haul travel: superb food, low-cost transport, and everything from Bangkok's chaos to island beaches. Guesthouses and street food make daily budgets remarkably low." },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Beyond the Bali Cliché', entryNote: 'Visa-on-arrival', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: "Indonesia rewards budget travellers who venture past the resorts. Bali's local warungs, Java's temples and the Gili Islands all cost little day to day, and inter-island travel is cheap." },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'Small Island, Huge Value', entryNote: 'eTA / eVisa', gettingThere: 'Long-haul flights', valueFeel: 'Outstanding',
      body: 'Sri Lanka packs beaches, tea-country hill towns, ancient cities and wildlife safaris into one compact, cheap island. Its scenic trains are among the world\'s great budget experiences.' },
    { countryName: 'India', countryCode: 'IN', subtitle: 'Unmatched Range on a Tiny Budget', entryNote: 'eVisa', gettingThere: 'Long-haul flights', valueFeel: 'Outstanding',
      body: "Few places stretch a British budget like India. From Rajasthan's forts to Kerala's backwaters, transport, food and lodging cost very little, and the cultural depth is limitless." },
    { countryName: 'Mexico', countryCode: 'MX', subtitle: 'Long-Haul, but Worth It', entryNote: 'Visa-free tourist entry', gettingThere: 'Long-haul flights', valueFeel: 'Good',
      body: "Mexico offers strong value once you're there: fresh, cheap street food, affordable domestic buses, and everything from Yucatán cenotes to Oaxaca's cuisine. Skip the pricey resort strips and travel like a local to unlock the real savings." },
    { countryName: 'Colombia', countryCode: 'CO', subtitle: "South America's Rising Bargain", entryNote: 'Visa-free short stay', gettingThere: 'Long-haul flights', valueFeel: 'Very good',
      body: "Colombia has become one of South America's best-value destinations: Medellín's spring-like climate, Cartagena's colonial charm and Andean coffee country all come cheap day to day." },
    { countryName: 'Tunisia', countryCode: 'TN', subtitle: 'Mediterranean Value on the Doorstep', entryNote: 'Visa-free short stay', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Tunisia rounds out the list as an underrated, close-to-home bargain: Mediterranean beaches, Roman ruins at Carthage and El Djem, and Saharan gateways, all at low daily costs. All-inclusive packages from the UK are frequently excellent value." },
  ],
  'cheapest-visa-free-countries-india-2026': [
    { countryName: 'Nepal', countryCode: 'NP', subtitle: "Nepal's Open Border, Unbeatable Value", entryNote: 'Visa-free (open border)', gettingThere: 'Land or short flight', valueFeel: 'Outstanding',
      body: 'Nepal is the single most affordable visa-free destination for Indian travellers. As neighbours sharing an open-border treaty, Indian citizens can enter without a passport (just an Aadhaar or voter ID) and without a visa. Kathmandu, Pokhara and the Annapurna trekking circuit offer world-class experiences at unbeatable prices.' },
    { countryName: 'Bhutan', countryCode: 'BT', subtitle: 'Free Entry, Uncrowded Himalayas', entryNote: 'Free entry for Indians (permit, not visa)', gettingThere: 'Flights via Kathmandu/Delhi', valueFeel: 'Outstanding',
      body: 'Unlike other nationalities who pay a $100/day sustainable development fee, Indian citizens enter Bhutan completely free — just a passport or voter ID. Bhutan is not technically visa-free but the arrangement is almost identical, and it is one of the most underrated budget destinations in Asia.' },
    { countryName: 'Sri Lanka', countryCode: 'LK', subtitle: 'Fast eVisa, Extraordinary Value', entryNote: 'eVisa (~$35)', gettingThere: 'Short direct flights', valueFeel: 'Outstanding',
      body: "Sri Lanka isn't fully visa-free, but the eVisa is fast and inexpensive, and once you're in, costs are extraordinarily low. Sri Lanka has re-emerged as one of Asia's best budget destinations — stunning beaches, ancient ruins, tea country and world-class surf." },
    { countryName: 'Maldives', countryCode: 'MV', subtitle: 'Skip the Resorts, Keep the Water', entryNote: 'Visa-free (30 days)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "The Maldives is visa-free for Indians with a 30-day stamp on arrival. The trick is knowing it doesn't have to be expensive: local-island guesthouses, as opposed to resort islands, offer beach rooms for a fraction of the overwater-bungalow price the marketing leads with. Maafushi Island is the budget-traveller favourite." },
    { countryName: 'Thailand', countryCode: 'TH', subtitle: '60 Days Visa-Free, Endless Value', entryNote: 'Visa-free (60 days)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: "Thailand extended visa-free access for Indian passport holders to 60 days in 2024 — a major upgrade. Thailand remains Asia's premier backpacker destination: Chiang Mai, Bangkok, Pai and the southern islands all offer incredible value." },
    { countryName: 'Malaysia', countryCode: 'MY', subtitle: 'Thailand-Level Value, Half the Crowds', entryNote: 'Visa-free (30 days)', gettingThere: 'Direct flights', valueFeel: 'Excellent',
      body: 'Malaysia is criminally underrated among Indian travellers — Kuala Lumpur, Penang and the Borneo islands offer a stunning variety of experiences at Thai-level prices. The food is extraordinary and cheap at hawker stalls, and transport infrastructure is excellent.' },
    { countryName: 'Indonesia', countryCode: 'ID', subtitle: 'Bali and Beyond, Visa-Free', entryNote: 'Visa-free (30 days)', gettingThere: 'Direct flights (Bali)', valueFeel: 'Very good',
      body: 'Bali is on every Indian traveller\'s radar, but Indian citizens can enter Indonesia without a visa for 30 days. Beyond Bali, Lombok, the Gili Islands, Yogyakarta and Komodo Island are all reachable on a single trip.' },
    { countryName: 'Jordan', countryCode: 'JO', subtitle: 'Petra on a Visa-on-Arrival', entryNote: 'Visa on arrival (~$50, sometimes waived)', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Petra and Wadi Rum are bucket-list destinations. Jordan isn't the cheapest, but the visa-on-arrival is simple, and the Jordan Pass covers entry to 40+ sites including Petra — excellent value for what it unlocks." },
    { countryName: 'South Africa', countryCode: 'ZA', subtitle: 'Cape Town, Now Genuinely Affordable', entryNote: 'Visa-free (30 days)', gettingThere: 'One-stop flights', valueFeel: 'Very good',
      body: "Indian passport holders get visa-free access to South Africa. Cape Town regularly ranks among the world's most beautiful cities, and with the rand's exchange rate, it has become genuinely affordable for Indian visitors." },
    { countryName: 'Kenya', countryCode: 'KE', subtitle: 'Safari Country on a Quick eVisa', entryNote: 'eVisa (~$50)', gettingThere: 'Direct flights (Nairobi)', valueFeel: 'Very good',
      body: "Kenya's eVisa is quick and easy. The payoff: the Maasai Mara during the Great Migration, Nairobi's food scene and Mount Kenya. The East African Tourism Visa also covers Uganda and Rwanda — strong value for a multi-country trip." },
    { countryName: 'Senegal', countryCode: 'SN', subtitle: "West Africa's Undiscovered Gem", entryNote: 'Visa-free', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: "West Africa's most stable and beautiful country — Dakar's beaches and music scene make it a completely undiscovered destination for Indian travellers." },
    { countryName: 'Rwanda', countryCode: 'RW', subtitle: 'Gorillas and a Fast eVisa', entryNote: 'eVisa (~$50)', gettingThere: 'One-stop flights (Kigali)', valueFeel: 'Good',
      body: "The land of gorilla trekking, a moving genocide memorial, and Africa's cleanest capital. The eVisa is fast and the experience is unlike anywhere else on this list." },
    { countryName: 'Tanzania', countryCode: 'TZ', subtitle: 'Zanzibar and Serengeti, One eVisa', entryNote: 'eVisa (~$50)', gettingThere: 'One-stop flights', valueFeel: 'Good',
      body: 'Zanzibar beaches plus Serengeti safaris — the eVisa covers the full country, making it one of the more accessible big-ticket safari trips on this list.' },
    { countryName: 'Philippines', countryCode: 'PH', subtitle: 'Cheapest Island-Hopping in Asia', entryNote: 'Visa-free (30 days)', gettingThere: 'Direct or one-stop flights', valueFeel: 'Good',
      body: '7,600 islands, extraordinary diving, and some of the cheapest island-hopping in Asia — a strong pick once the more obvious visa-free destinations are covered.' },
    { countryName: 'Fiji', countryCode: 'FJ', subtitle: 'A Pacific Surprise, Visa-Free', entryNote: 'Visa-free (4 months)', gettingThere: 'Long-haul, multi-stop', valueFeel: 'Good',
      body: 'A surprise entry on any Indian traveller\'s list — Indian citizens get four months visa-free. Beach budget guesthouses keep daily costs reasonable despite the long-haul routing.' },
  ],
}
