// Thin wrapper around the OpenNext-generated Cloudflare Worker.
//
// `.open-next/worker.js` is fully regenerated by `npm run cf:build` on every
// deploy, so it can't carry our own additions — it only exports `fetch`. This
// file lives outside `.open-next/` (survives rebuilds) and re-exports that
// handler unchanged, adding a `scheduled` handler for the Cloudflare Cron
// Trigger declared in wrangler.jsonc (`triggers.crons`).
//
// The scheduled handler calls back into the Next.js app over the existing
// WORKER_SELF_REFERENCE service binding (already declared in wrangler.jsonc,
// previously unused) rather than reimplementing any logic here — this stays
// a thin trigger, all the real work (queries, Resend sends, idempotency
// guards) lives in the normal Next.js route handlers, authenticated the same
// way a manual/CLI cron hit already is (CRON_SECRET bearer token).
// Generated by `opennextjs-cloudflare build`; may not exist yet when Next's
// own `next build` (and its typecheck) runs on a clean checkout, since that
// build step is what generates it. Ts-ignore (not ts-expect-error) below
// because whether this errors depends on local build state — real bundling
// (wrangler, at actual deploy time) always sees the real file either way.
// @ts-ignore
import opennextHandler, { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js'

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge }

async function hitRoute(env: Env, path: string) {
  // CRON_SECRET is a `wrangler secret put` value — not a declared binding, so
  // it isn't in the generated Env type, but it is present on env at runtime.
  const secret = (env as unknown as { CRON_SECRET?: string }).CRON_SECRET
  const url = `https://visitplane.com${path}${secret ? `?secret=${secret}` : ''}`
  try {
    const res = await env.WORKER_SELF_REFERENCE.fetch(new Request(url))
    console.log(`[cron] ${path} -> ${res.status}`)
  } catch (e) {
    console.error(`[cron] ${path} failed:`, (e as Error).message)
  }
}

export default {
  fetch: opennextHandler.fetch,
  async scheduled(_event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    // Revives the existing (dormant since the Vercel->Cloudflare migration)
    // welcome-sequence flow worker, plus the new lifecycle re-engagement
    // tracks — one daily trigger, two independent route handlers.
    ctx.waitUntil(hitRoute(env, '/api/cron/flows'))
    ctx.waitUntil(hitRoute(env, '/api/cron/lifecycle'))
  },
}
