// Thin wrapper around the OpenNext-generated Cloudflare Worker.
//
// `.open-next/worker.js` is fully regenerated by `npm run cf:build` on every
// deploy, so it can't carry our own additions — it only exports `fetch`. This
// file lives outside `.open-next/` (survives rebuilds) and re-exports that
// handler unchanged, adding a `scheduled` handler for the Cloudflare Cron
// Trigger declared in wrangler.jsonc (`triggers.crons`).
//
// The scheduled handler calls back into the Next.js app over the existing
// WORKER_SELF_REFERENCE service binding (already declared in wrangler.jsonc,
// previously unused) rather than reimplementing any logic here — this stays
// a thin trigger, all the real work (queries, Resend sends, idempotency
// guards) lives in the normal Next.js route handlers, authenticated the same
// way a manual/CLI cron hit already is (CRON_SECRET bearer token).
// Generated by `opennextjs-cloudflare build`; may not exist yet when Next's
// own `next build` (and its typecheck) runs on a clean checkout, since that
// build step is what generates it. Ts-ignore (not ts-expect-error) below
// because whether this errors depends on local build state — real bundling
// (wrangler, at actual deploy time) always sees the real file either way.
// @ts-ignore
import opennextHandler, { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from './.open-next/worker.js'

export { DOQueueHandler, DOShardedTagCache, BucketCachePurge }

async function hitRoute(env: Env, path: string) {
  // CRON_SECRET is a `wrangler secret put` value — not a declared binding, so
  // it isn't in the generated Env type, but it is present on env at runtime.
  const secret = (env as unknown as { CRON_SECRET?: string }).CRON_SECRET
  const url = `https://visitplane.com${path}${secret ? `?secret=${secret}` : ''}`
  try {
    const res = await env.WORKER_SELF_REFERENCE.fetch(new Request(url))
    console.log(`[cron] ${path} -> ${res.status}`)
  } catch (e) {
    console.error(`[cron] ${path} failed:`, (e as Error).message)
  }
}

// Cloudflare-billing root cause: open-next.config.ts intentionally runs with
// the no-op "dummy" incremental cache (no R2/KV binding — see that file), so
// `export const revalidate` in the ISR pages (visa pairs, /seo/*, /blog,
// /destinations) never persists a rendered page between requests. Verified
// live: every request to /visa/[passport]/[destination] came back
// `x-nextjs-cache: MISS` with a fresh 2-4s Supabase-backed render, even though
// the response already carries a correct `cache-control: s-maxage=2592000`.
// Cloudflare's edge never cached it either — no `cf-cache-status` header was
// present, meaning nothing in front of this Worker was reading that header.
// This wraps the existing handler with Cloudflare's built-in per-zone Cache
// API (`caches.default`, free, no R2/KV/card, distinct from the incremental
// cache above) so a response the app already marked shareable is served from
// the edge on repeat requests instead of re-invoking the Worker. Gated on the
// ORIGIN response's own Cache-Control (never on the route) so force-dynamic /
// admin / API responses — which already emit `private, no-store` — are
// untouched; verified live against /admin/login, /portal/login, /order and
// /api routes before shipping this.
function isEdgeCacheable(response: Response): boolean {
  if (response.status !== 200) return false
  if (response.headers.has('set-cookie')) return false
  const cacheControl = response.headers.get('cache-control') ?? ''
  if (!cacheControl) return false
  if (/private|no-store/i.test(cacheControl)) return false
  return /s-maxage/i.test(cacheControl)
}

export default {
  async fetch(request: Request, env: Env, ctx: ExecutionContext) {
    const isGet = request.method === 'GET'
    // @ts-ignore — `caches.default` is a Workers-runtime global, not in the
    // standard lib.dom typings this project's tsconfig pulls in.
    const cache: Cache = caches.default
    const cacheKey = new Request(request.url, request)

    if (isGet) {
      const cached = await cache.match(cacheKey)
      if (cached) return cached
    }

    const response: Response = await opennextHandler.fetch(request, env, ctx)

    if (isGet && isEdgeCacheable(response)) {
      ctx.waitUntil(cache.put(cacheKey, response.clone()))
    }

    return response
  },
  async scheduled(_event: ScheduledEvent, env: Env, ctx: ExecutionContext) {
    // Revives the existing (dormant since the Vercel->Cloudflare migration)
    // welcome-sequence flow worker, plus the new lifecycle re-engagement
    // tracks — one daily trigger, two independent route handlers.
    ctx.waitUntil(hitRoute(env, '/api/cron/flows'))
    ctx.waitUntil(hitRoute(env, '/api/cron/lifecycle'))
  },
}
