// AUTO-GENERATED by scripts/sprint5_prune.py — Sprint 5 content prune.
// Redirected blog slugs (301'd to a survivor). Used to trim the sitemap.
// Reversible: removing entries restores the page. No content deleted.
export const redirectedSlugs: string[] = [
  "bangladesh-to-france-schengen-visa-requirements-2026",
  "bangladesh-to-germany-schengen-visa-requirements-2026",
  "best-time-to-visit-united-arab-emirates-weather-seasons-cheapest-months-2026",
  "how-to-write-a-winning-sop-for-a-ireland-student-visa-with-sample",
  "india-to-australia-visa-requirements-how-to-apply-2026",
  "india-to-germany-visa-schengen-requirements-how-to-apply-2026",
  "india-to-malaysia-visa-requirements-how-to-apply-2026",
  "india-to-qatar-visa-requirements-how-to-apply-2026",
  "india-to-singapore-visa-requirements-how-to-apply-2026",
  "india-to-spain-schengen-visa-requirements-2026",
  "india-to-switzerland-schengen-visa-requirements-2026",
  "nigeria-to-australia-visa-requirements-2026",
  "nigeria-to-germany-schengen-visa-requirements-2026",
  "nigeria-to-turkey-visa-requirements-how-to-apply-2026",
  "pakistan-to-australia-visa-requirements-how-to-apply-2026",
  "pakistan-to-azerbaijan-visa-requirements-how-to-apply-2026",
  "pakistan-to-france-schengen-visa-requirements-2026",
  "pakistan-to-germany-schengen-visa-requirements-2026",
  "pakistan-to-greece-schengen-visa-requirements-2026",
  "pakistan-to-netherlands-schengen-visa-requirements-2026",
  "pakistan-to-turkey-visa-requirements-how-to-apply-2026",
  "tokyo-travel-guide-top-things-to-do-costs-visa-tips-2026",
  "united-arab-emirates-visa-processing-time-from-egypt-how-long-it-really-takes-20",
  "united-kingdom-vs-canada-visa-for-india-which-is-easier-to-get-2026",
  "united-kingdom-vs-canada-visa-for-pakistan-which-is-easier-to-get-2026",
  "united-states-vs-canada-visa-for-bangladesh-which-is-easier-to-get-2026",
  "united-states-vs-canada-visa-for-nigeria-which-is-easier-to-get-2026",
]

export const redirectedSlugSet = new Set(redirectedSlugs)
