-- Seed the 60 unique countries referenced across the 15 in-scope
-- "15-cheapest-countries" listicle posts. Source of truth for this list is
-- scripts/destination-photos/countries.mjs — keep the two in sync by hand.
-- Applied to project wmoywcqadkjxujgwduup.

insert into public.destination_photo_countries (country_code, country_name, region, avg_daily_cost_usd) values
  ('AL', 'Albania', 'Europe', 45),
  ('AZ', 'Azerbaijan', 'Caucasus', 45),
  ('BB', 'Barbados', 'Caribbean', 110),
  ('BJ', 'Benin', 'West Africa', 35),
  ('BT', 'Bhutan', 'South Asia', 65),
  ('BO', 'Bolivia', 'South America', 35),
  ('BW', 'Botswana', 'Southern Africa', 60),
  ('BN', 'Brunei', 'Southeast Asia', 55),
  ('BG', 'Bulgaria', 'Europe', 40),
  ('BF', 'Burkina Faso', 'West Africa', 30),
  ('CV', 'Cabo Verde', 'West Africa', 55),
  ('KH', 'Cambodia', 'Southeast Asia', 30),
  ('CN', 'China', 'East Asia', 55),
  ('CO', 'Colombia', 'South America', 35),
  ('CI', 'Côte d''Ivoire', 'West Africa', 45),
  ('EG', 'Egypt', 'North Africa', 35),
  ('ET', 'Ethiopia', 'East Africa', 30),
  ('FJ', 'Fiji', 'Pacific', 75),
  ('GE', 'Georgia', 'Caucasus', 35),
  ('GH', 'Ghana', 'West Africa', 40),
  ('GT', 'Guatemala', 'Central America', 35),
  ('HK', 'Hong Kong', 'East Asia', 90),
  ('IN', 'India', 'South Asia', 30),
  ('ID', 'Indonesia', 'Southeast Asia', 30),
  ('JO', 'Jordan', 'Middle East', 55),
  ('KE', 'Kenya', 'East Africa', 45),
  ('KG', 'Kyrgyzstan', 'Central Asia', 30),
  ('LA', 'Laos', 'Southeast Asia', 30),
  ('MY', 'Malaysia', 'Southeast Asia', 35),
  ('MV', 'Maldives', 'South Asia', 120),
  ('MU', 'Mauritius', 'East Africa', 90),
  ('MX', 'Mexico', 'North America', 45),
  ('MA', 'Morocco', 'North Africa', 40),
  ('MM', 'Myanmar', 'Southeast Asia', 30),
  ('NP', 'Nepal', 'South Asia', 30),
  ('NG', 'Nigeria', 'West Africa', 45),
  ('PE', 'Peru', 'South America', 35),
  ('PH', 'Philippines', 'Southeast Asia', 35),
  ('PT', 'Portugal', 'Europe', 60),
  ('QA', 'Qatar', 'Middle East', 90),
  ('RW', 'Rwanda', 'East Africa', 45),
  ('SN', 'Senegal', 'West Africa', 45),
  ('SC', 'Seychelles', 'East Africa', 130),
  ('SL', 'Sierra Leone', 'West Africa', 35),
  ('SG', 'Singapore', 'Southeast Asia', 90),
  ('ZA', 'South Africa', 'Southern Africa', 50),
  ('LK', 'Sri Lanka', 'South Asia', 35),
  ('ST', 'São Tomé & Príncipe', 'West Africa', 55),
  ('TZ', 'Tanzania', 'East Africa', 50),
  ('TH', 'Thailand', 'Southeast Asia', 35),
  ('GM', 'The Gambia', 'West Africa', 35),
  ('TL', 'Timor-Leste', 'Southeast Asia', 40),
  ('TG', 'Togo', 'West Africa', 35),
  ('TN', 'Tunisia', 'North Africa', 35),
  ('TR', 'Turkey', 'Europe/Middle East', 40),
  ('AE', 'United Arab Emirates', 'Middle East', 90),
  ('UG', 'Uganda', 'East Africa', 40),
  ('VN', 'Vietnam', 'Southeast Asia', 30),
  ('ZM', 'Zambia', 'Southern Africa', 50),
  ('ZW', 'Zimbabwe', 'Southern Africa', 45)
on conflict (country_code) do update set
  country_name = excluded.country_name,
  region = excluded.region,
  avg_daily_cost_usd = excluded.avg_daily_cost_usd;
